import type { Session, User } from "@supabase/supabase-js";

export const DEMO_INVESTOR_USERNAME = "investor";
export const DEMO_INVESTOR_EMAIL = "investor@bahoil.demo";
const DEMO_INVESTOR_PASSWORD = import.meta.env.VITE_DEMO_INVESTOR_PASSWORD || "";
export const DEMO_INVESTOR_ID = "00000000-0000-4000-8000-000000000001";
export const DEMO_SESSION_STORAGE_KEY = "bah_investor_demo_session";

const DEMO_ASSET_CREATED_AT = "2026-05-24T00:00:00Z";
const MIME_PDF = "application/pdf";
const MIME_XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
const MIME_DOCX = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
const MIME_MP4 = "video/mp4";
const MIME_MOV = "video/quicktime";

type DemoUserLike = {
  id?: string;
  email?: string;
  user_metadata?: Record<string, unknown>;
} | null | undefined;

export interface DemoInvestorDocument {
  id: string;
  title: string;
  description: string | null;
  created_at: string;
  category: "overview" | "pitch" | "financials" | "mapping" | "operations" | "field_videos" | "management";
  asset_type: "document" | "video" | "image";
  file_size: number | null;
  mime_type: string | null;
  original_filename: string | null;
  thumbnail_path: string | null;
  sort_order: number;
  is_featured: boolean;
}

export const demoInvestorDocuments: DemoInvestorDocument[] = [
  {
    id: "demo-start-here",
    title: "Start Here: Investor Review Path",
    description: "Plain-English orientation for how approved investors review private overview, financial, technical, operating, field, and management materials.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "overview",
    asset_type: "document",
    file_size: 92 * 1024,
    mime_type: MIME_PDF,
    original_filename: "Investor Review Path.pdf",
    thumbnail_path: null,
    sort_order: 1,
    is_featured: true,
  },
  {
    id: "demo-investor-teaser",
    title: "Investor Teaser",
    description: "Concise first-read narrative for approved investors before they review the full private deck.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "pitch",
    asset_type: "document",
    file_size: 85621,
    mime_type: MIME_PDF,
    original_filename: "Investor Teaser.pdf",
    thumbnail_path: null,
    sort_order: 1,
    is_featured: false,
  },
  {
    id: "demo-opportunity-snapshot",
    title: "Opportunity Snapshot",
    description: "Concise investor snapshot covering structure, review sequence, and core private materials available in the BAH deal room.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "pitch",
    asset_type: "document",
    file_size: 76088,
    mime_type: MIME_PDF,
    original_filename: "BAH Oil - Opportunity Snapshot.pdf",
    thumbnail_path: null,
    sort_order: 2,
    is_featured: false,
  },
  {
    id: "demo-pitch-deck",
    title: "Investor Overview Deck",
    description: "Primary investor overview deck for approved private review.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "pitch",
    asset_type: "document",
    file_size: 1921547,
    mime_type: MIME_PDF,
    original_filename: "BAH Oil - Investor Overview Deck.pdf",
    thumbnail_path: null,
    sort_order: 3,
    is_featured: false,
  },
  {
    id: "demo-overview-memo",
    title: "Investor Overview Memorandum",
    description: "Long-form private narrative that supports the deck with additional review context and background.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "pitch",
    asset_type: "document",
    file_size: 94117,
    mime_type: MIME_PDF,
    original_filename: "Investor Overview Memorandum.pdf",
    thumbnail_path: null,
    sort_order: 4,
    is_featured: false,
  },
  {
    id: "demo-budget-support",
    title: "Budget Support",
    description: "Spreadsheet-style support for project cost detail, capital-call support, and expenditure review.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "financials",
    asset_type: "document",
    file_size: 34100,
    mime_type: MIME_XLSX,
    original_filename: "Budget Support.xlsx",
    thumbnail_path: null,
    sort_order: 1,
    is_featured: false,
  },
  {
    id: "demo-financial-model",
    title: "Financial Review Model",
    description: "Locked-cell model slot for investor economics, assumptions, distribution review, and tax-framing discussion.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "financials",
    asset_type: "document",
    file_size: 195315,
    mime_type: MIME_XLSX,
    original_filename: "Financial Review Model.xlsx",
    thumbnail_path: null,
    sort_order: 2,
    is_featured: false,
  },
  {
    id: "demo-technical-economics",
    title: "Technical Economics Appendix",
    description: "Private technical appendix slot for the asset case and economic support materials.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "financials",
    asset_type: "document",
    file_size: 87669,
    mime_type: MIME_PDF,
    original_filename: "Technical Economics Appendix.pdf",
    thumbnail_path: null,
    sort_order: 3,
    is_featured: false,
  },
  {
    id: "demo-financial-summary",
    title: "Financial Summary",
    description: "One-page reference slot for the quick financial summary investors can review before opening the full model.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "financials",
    asset_type: "document",
    file_size: 5753,
    mime_type: MIME_PDF,
    original_filename: "Financial Summary.pdf",
    thumbnail_path: null,
    sort_order: 4,
    is_featured: false,
  },
  {
    id: "demo-mapping-deck",
    title: "Technical Mapping Deck",
    description: "Technical appendix slot for subsurface mapping support and geologic review materials.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "mapping",
    asset_type: "document",
    file_size: 2083135,
    mime_type: MIME_PDF,
    original_filename: "Technical Mapping Deck.pdf",
    thumbnail_path: null,
    sort_order: 1,
    is_featured: false,
  },
  {
    id: "demo-operations-sequence-01",
    title: "Primary Operations Sequence",
    description: "Primary operations video for site activity, operating context, and tangible field evidence.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "operations",
    asset_type: "video",
    file_size: 390306062,
    mime_type: MIME_MOV,
    original_filename: "operations-sequence-01.mov",
    thumbnail_path: null,
    sort_order: 1,
    is_featured: false,
  },
  {
    id: "demo-operations-sequence-02",
    title: "Extended Operations Sequence",
    description: "Extended portrait operations footage prepared for private investor review.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "operations",
    asset_type: "video",
    file_size: 200119556,
    mime_type: MIME_MOV,
    original_filename: "operations-sequence-02.mov",
    thumbnail_path: null,
    sort_order: 2,
    is_featured: false,
  },
  {
    id: "demo-operations-sequence-03",
    title: "Operations Sequence Cut",
    description: "Mid-length operations clip providing field context and visible operating activity.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "operations",
    asset_type: "video",
    file_size: 137037413,
    mime_type: MIME_MOV,
    original_filename: "operations-sequence-03.mov",
    thumbnail_path: null,
    sort_order: 3,
    is_featured: false,
  },
  {
    id: "demo-operations-sequence-04",
    title: "Vertical Operations Review",
    description: "Vertical operations footage for reviewing field conditions and activity sequence.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "operations",
    asset_type: "video",
    file_size: 120019286,
    mime_type: MIME_MP4,
    original_filename: "operations-sequence-04.mp4",
    thumbnail_path: null,
    sort_order: 4,
    is_featured: false,
  },
  {
    id: "demo-operations-sequence-05",
    title: "Landscape Operations Review",
    description: "Landscape operations footage prepared for broad field-context review.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "operations",
    asset_type: "video",
    file_size: 102725995,
    mime_type: MIME_MP4,
    original_filename: "operations-sequence-05.mp4",
    thumbnail_path: null,
    sort_order: 5,
    is_featured: false,
  },
  {
    id: "demo-operations-image-01",
    title: "Operations Reference Image",
    description: "Private field reference image supporting the operations review materials.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "operations",
    asset_type: "image",
    file_size: 848586,
    mime_type: "image/heic",
    original_filename: "operations-reference-image.heic",
    thumbnail_path: null,
    sort_order: 6,
    is_featured: false,
  },
  {
    id: "demo-field-video-01",
    title: "Featured Short Field Clip",
    description: "Featured short field clip selected for quick operational context.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 80562382,
    mime_type: MIME_MOV,
    original_filename: "field-clip-01.mov",
    thumbnail_path: null,
    sort_order: 1,
    is_featured: false,
  },
  {
    id: "demo-field-video-02",
    title: "High-Resolution Field Clip",
    description: "High-resolution field clip for reviewing equipment, access, and site activity.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 76876961,
    mime_type: MIME_MP4,
    original_filename: "field-clip-02.mp4",
    thumbnail_path: null,
    sort_order: 2,
    is_featured: false,
  },
  {
    id: "demo-field-video-03",
    title: "Compact Portrait Field Clip",
    description: "Short portrait field clip for concise private review.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 63711111,
    mime_type: MIME_MOV,
    original_filename: "field-clip-03.mov",
    thumbnail_path: null,
    sort_order: 3,
    is_featured: false,
  },
  {
    id: "demo-field-video-04",
    title: "Landscape Field Clip",
    description: "Medium landscape field clip prepared for broad browser playback.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 35162278,
    mime_type: MIME_MP4,
    original_filename: "field-clip-04.mp4",
    thumbnail_path: null,
    sort_order: 4,
    is_featured: false,
  },
  {
    id: "demo-field-video-05",
    title: "Supplemental Field Angle",
    description: "Supplemental field angle showing the same operating area from a separate vantage point.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 35162278,
    mime_type: MIME_MP4,
    original_filename: "field-clip-05.mp4",
    thumbnail_path: null,
    sort_order: 5,
    is_featured: false,
  },
  {
    id: "demo-field-video-06",
    title: "Medium Landscape Field Clip",
    description: "Supporting field clip for additional operating context.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 29880161,
    mime_type: MIME_MP4,
    original_filename: "field-clip-06.mp4",
    thumbnail_path: null,
    sort_order: 6,
    is_featured: false,
  },
  {
    id: "demo-field-video-07",
    title: "Short Landscape Field Clip",
    description: "Compact landscape clip reserved for private field playback.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 21673533,
    mime_type: MIME_MP4,
    original_filename: "field-clip-07.mp4",
    thumbnail_path: null,
    sort_order: 7,
    is_featured: false,
  },
  {
    id: "demo-field-video-08",
    title: "Eight-Second Field Clip",
    description: "Very short portrait clip suitable for a fast-loading private preview card.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 18913282,
    mime_type: MIME_MOV,
    original_filename: "field-clip-08.mov",
    thumbnail_path: null,
    sort_order: 8,
    is_featured: false,
  },
  {
    id: "demo-field-video-09",
    title: "Longer Compact Field Clip",
    description: "Compact vertical clip for quick review of field conditions.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 16024037,
    mime_type: MIME_MP4,
    original_filename: "field-clip-09.mp4",
    thumbnail_path: null,
    sort_order: 9,
    is_featured: false,
  },
  {
    id: "demo-field-video-10",
    title: "Short Equipment Clip",
    description: "Short landscape equipment clip supporting operational review.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 14789105,
    mime_type: MIME_MP4,
    original_filename: "field-clip-10.mp4",
    thumbnail_path: null,
    sort_order: 10,
    is_featured: false,
  },
  {
    id: "demo-field-video-11",
    title: "Supplemental Equipment Angle",
    description: "Additional short equipment angle retained for private operating context.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 14789105,
    mime_type: MIME_MP4,
    original_filename: "field-clip-11.mp4",
    thumbnail_path: null,
    sort_order: 11,
    is_featured: false,
  },
  {
    id: "demo-field-video-12",
    title: "Vertical Operations Cutaway",
    description: "Very short vertical clip for quick operational context.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 8121708,
    mime_type: MIME_MP4,
    original_filename: "field-clip-12.mp4",
    thumbnail_path: null,
    sort_order: 12,
    is_featured: false,
  },
  {
    id: "demo-field-video-13",
    title: "Compact Field Clip",
    description: "Small vertical field clip for quick private preview.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 7035474,
    mime_type: MIME_MP4,
    original_filename: "field-clip-13.mp4",
    thumbnail_path: null,
    sort_order: 13,
    is_featured: false,
  },
  {
    id: "demo-field-video-14",
    title: "Four-Second Landscape Loop",
    description: "Ultra-short landscape clip capturing a quick field proof point.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 4993651,
    mime_type: MIME_MP4,
    original_filename: "field-clip-14.mp4",
    thumbnail_path: null,
    sort_order: 14,
    is_featured: false,
  },
  {
    id: "demo-field-video-15",
    title: "Short Vertical Field Clip",
    description: "Five-second vertical field clip for fast private review.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 3219975,
    mime_type: MIME_MP4,
    original_filename: "field-clip-15.mp4",
    thumbnail_path: null,
    sort_order: 15,
    is_featured: false,
  },
  {
    id: "demo-field-video-16",
    title: "Three-Second Vertical Clip",
    description: "Brief vertical field clip for a quick operational proof point.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "field_videos",
    asset_type: "video",
    file_size: 1615716,
    mime_type: MIME_MP4,
    original_filename: "field-clip-16.mp4",
    thumbnail_path: null,
    sort_order: 16,
    is_featured: false,
  },
  {
    id: "demo-management-cv-pdf",
    title: "Technical Leadership CV",
    description: "Management and technical authority slot for the engineering/geology credentials packet.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "management",
    asset_type: "document",
    file_size: 226220,
    mime_type: MIME_PDF,
    original_filename: "Technical Advisor Background.pdf",
    thumbnail_path: null,
    sort_order: 1,
    is_featured: false,
  },
  {
    id: "demo-management-cv-source",
    title: "Technical Leadership Background",
    description: "Supporting background packet for technical leadership credentials.",
    created_at: DEMO_ASSET_CREATED_AT,
    category: "management",
    asset_type: "document",
    file_size: 60010,
    mime_type: MIME_DOCX,
    original_filename: "Technical Advisor Background.docx",
    thumbnail_path: null,
    sort_order: 2,
    is_featured: false,
  },
];

export const isDemoLogin = (identifier: string, password: string) => {
  const normalizedIdentifier = identifier.trim().toLowerCase();
  return (
    DEMO_INVESTOR_PASSWORD.length > 0 &&
    password === DEMO_INVESTOR_PASSWORD &&
    (normalizedIdentifier === DEMO_INVESTOR_USERNAME || normalizedIdentifier === DEMO_INVESTOR_EMAIL)
  );
};

export const isDemoInvestorUser = (user: DemoUserLike) => {
  return Boolean(
    user?.id === DEMO_INVESTOR_ID ||
    user?.email === DEMO_INVESTOR_EMAIL ||
    user?.user_metadata?.demo_user === true,
  );
};

export const hasStoredDemoSession = () => {
  return typeof window !== "undefined" && window.localStorage.getItem(DEMO_SESSION_STORAGE_KEY) === "active";
};

export const storeDemoSession = () => {
  if (typeof window !== "undefined") window.localStorage.setItem(DEMO_SESSION_STORAGE_KEY, "active");
};

export const clearDemoSession = () => {
  if (typeof window !== "undefined") window.localStorage.removeItem(DEMO_SESSION_STORAGE_KEY);
};

export const createDemoUser = (): User => ({
  id: DEMO_INVESTOR_ID,
  aud: "authenticated",
  role: "authenticated",
  email: DEMO_INVESTOR_EMAIL,
  email_confirmed_at: "2026-05-24T00:00:00Z",
  phone: "",
  confirmed_at: "2026-05-24T00:00:00Z",
  last_sign_in_at: new Date().toISOString(),
  app_metadata: { provider: "demo", providers: ["demo"] },
  user_metadata: {
    full_name: "BAH Investor Demo",
    role: "investor",
    demo_user: true,
  },
  identities: [],
  created_at: "2026-05-24T00:00:00Z",
  updated_at: new Date().toISOString(),
} as User);

export const createDemoSession = (): Session => ({
  access_token: "demo-investor-access-token",
  refresh_token: "demo-investor-refresh-token",
  expires_in: 24 * 60 * 60,
  expires_at: Math.floor(Date.now() / 1000) + 24 * 60 * 60,
  token_type: "bearer",
  user: createDemoUser(),
} as Session);
